export const LOADING_DATA = 'LOADING_DATA'

export const FETCH_DATA = 'FETCH_DATA'

export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR'

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'

export const SAVE_CATEGORIES = 'SAVE_CATEGORIES'

export const SAVE_SEARCH = 'SAVE_SEARCH'

export const CLEAN_FILTER = 'CLEAN_FILTER'

export const SET_CLEAR = 'SET_CLEAR'
